-- Migration: achievement_collections_complete_5
-- Auto-generated by scripts/generate-achievement.ts. Review the proposal in
-- the PR description before merging — Claude can be fooled into proposing
-- duplicates the cross-check missed (e.g. semantic dup with a different code).
--
-- Rollback:
--   delete from public.achievements where code = 'collections_complete_5';

insert into public.achievements (code, title, description, icon, xp_reward, condition, sort_order)
values (
  'collections_complete_5',
  'Master Collector',
  'You complete 5 full collections, proving you never leave a hunt unfinished.',
  '🗂️',
  150,
  '{"kind":"collections_complete","gte":5}'::jsonb,
  80
)
on conflict (code) do update
  set title       = excluded.title,
      description = excluded.description,
      icon        = excluded.icon,
      xp_reward   = excluded.xp_reward,
      condition   = excluded.condition,
      sort_order  = excluded.sort_order;
