-- Migration: collection_window_displays_storefronts
-- Auto-generated by scripts/generate-collection.ts (multi-agent pipeline).
-- Review the title, item names, and ai_hints before merging — Claude can be
-- fooled into proposing a near-duplicate of an existing collection that the
-- normalised name check missed.
--
-- Topic rationale: Window displays are abundant in every shopping district and high street, offering photographers endless variety in composition, lighting, and merchandising styles without requiring special access. This topic is distinct from "Architectural Styles" and "Street Art" — it focuses on the curated visual narratives of retail rather than built form or wall-based artwork, making it fresh and highly photographable for urban explorers.
-- Generation: model=claude-haiku-4-5-20251001 input=7982 output=3319 cache_read=0 cache_write=0
--
-- Idempotent — relies on collections_system_title_uniq (migration 015).
-- Re-applying skips the collection insert and is a no-op (items insert is
-- gated on the new id, so it only fires when the parent insert succeeded).
--
-- Rollback:
--   delete from public.collections
--    where creator_id = '00000000-0000-0000-0000-000000000001' and title = 'Window Displays & Storefronts';

with new_coll as (
  insert into public.collections (
    creator_id, title, description, category, cover_image_url, is_public, is_freeform
  )
  values (
    '00000000-0000-0000-0000-000000000001',
    'Window Displays & Storefronts',
    'A photography collection documenting the visual appeal and creativity of retail window displays and storefronts in urban environments. This collection captures the artistry, merchandising strategies, seasonal themes, and architectural details that make street-level retail spaces engaging and photogenic subjects in cities.',
    'urban'::public.collection_category,
    'https://upload.wikimedia.org/wikipedia/commons/9/96/Clothes.jpg',
    true,
    false
  )
  on conflict (creator_id, title) do nothing
  returning id
)
insert into public.collection_items (
  collection_id, name, description, ai_validation_prompt, rarity, fun_fact, example_image_url, sort_order
)
select new_coll.id, x.name, x.description, x.ai_validation_prompt, x.rarity, x.fun_fact, x.example_image_url, x.sort_order
from new_coll
cross join (values
    ('Mannequin in formal wear', 'Look for a dress form wearing a suit, tuxedo, or elegant gown positioned prominently in the window to catch the eye.', 'Identify a human-shaped mannequin wearing a suit, dress, tuxedo, or formal attire clearly visible in a storefront window.', 'common'::public.item_rarity, 'Early mannequins were carved from wood and could cost as much as a car; department stores kept them locked in safes overnight.', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Clothes.jpg', 0),
    ('Neon storefront sign', 'Photograph glowing neon tubes spelling out a business name or logo, especially at dusk or night for the brightest colors.', 'Detect glowing neon tubing forming letters, words, or symbols on or above a storefront entrance, visible against the storefront structure.', 'common'::public.item_rarity, 'Neon signs can last 10-15 years continuously lit without darkening, unlike incandescent bulbs that burn out in months.', 'https://upload.wikimedia.org/wikipedia/commons/2/2a/WikiSam_the_Record_Man.jpg', 1),
    ('Vintage shop window', 'Find a cluttered, eclectic display of retro items like old records, furniture, or clothes arranged with nostalgic charm.', 'Recognize a window display featuring aged or antique-style merchandise, worn furniture, retro signage, or items from past decades.', 'uncommon'::public.item_rarity, 'Antique shop windows became popular specifically because they reduced foot traffic theft—customers felt watched by all those old eyes.', null, 2),
    ('Luxury brand display', 'Capture a sleek, minimalist window with high-end products, polished surfaces, and plenty of empty space around each item.', 'Show a high-end brand name, designer logo, or premium product presentation with minimalist, elegant display staging visible in the window.', 'common'::public.item_rarity, 'High-end retailers intentionally leave portions of windows empty; sparse displays signal exclusivity and discourage bargain hunters.', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Foie_gras_with_sauternes.jpg', 3),
    ('Seasonal window decoration', 'Look for holiday-themed displays with seasonal colors, ornaments, garlands, or props celebrating current holidays or seasons.', 'Display seasonal decorations such as holiday lights, festive garlands, themed props, or seasonal merchandise clearly visible in the storefront window.', 'common'::public.item_rarity, 'Department store holiday windows began as a way to prevent shoplifting—elaborate displays forced customers into monitored entrances.', 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Macrame_.jpg', 4),
    ('Reflected street scene in glass', 'Position yourself to capture the storefront glass reflecting clouds, buildings, people, and traffic from the street behind you.', 'Capture a storefront glass window pane reflecting street elements like pedestrians, vehicles, buildings, or sky clearly visible in the reflection.', 'common'::public.item_rarity, 'Store windows are typically angled 5-10 degrees outward to reduce street reflections and force eye contact with displays, not just a reflection of yourself.', null, 5),
    ('Art gallery storefront', 'Photograph white walls with carefully lit artwork, sculptures, or installations displayed with intentional spacing and lighting.', 'Show framed artwork, paintings, sculptures, or artistic pieces displayed in the gallery window with clean, minimalist presentation.', 'uncommon'::public.item_rarity, 'Gallery windows intentionally display art at slightly above eye level to trigger sustained viewing—our eyes naturally follow objects placed higher.', null, 6),
    ('Fashion boutique entrance', 'Find an inviting entryway with stylish clothing displayed on hangers or forms, with appealing signage and welcoming lighting.', 'Display fashionable clothing, garments, or accessory items arranged stylishly in a boutique-style window with refined presentation.', 'common'::public.item_rarity, 'Boutique windows use asymmetrical displays because humans spend 60% more time looking at slightly off-center compositions than perfectly centered ones.', 'https://upload.wikimedia.org/wikipedia/commons/4/43/Bakerresize.jpg', 7),
    ('Bookstore window arrangement', 'Look for stacked or fanned books, often with a theme or author spotlight, arranged to draw readers into the store.', 'Show stacked books, book covers, or reading materials prominently displayed with organized or creative book presentation in the window.', 'common'::public.item_rarity, 'Bookstore windows stack books spine-out at varied angles; uniform shelving actually reduces purchases by signaling the store is ''finished.''', null, 8),
    ('Antique shop display', 'Capture a dense window packed with vintage treasures like furniture, glassware, mirrors, and oddities piled together.', 'Recognize vintage furniture, old collectibles, period pieces, or aged decorative items visibly arranged in the shop window.', 'uncommon'::public.item_rarity, 'Crowded antique shop windows increase perceived value—buyers interpret density as evidence of authenticity and rarity.', null, 9),
    ('Florist window with fresh flowers', 'Photograph bright, colorful bunches of cut flowers and blooming plants arranged in vases and buckets in the window.', 'Display fresh flowers, blooms, flower arrangements, or potted plants prominently visible in the florist''s storefront window.', 'common'::public.item_rarity, 'Florists change window displays every 2-3 days partly because customers unconsciously avoid stores with ''dead-looking'' flowers, even if they''re still fresh.', 'https://upload.wikimedia.org/wikipedia/commons/2/24/A_Parisian_Flower_Market.jpg', 10),
    ('Jewelry store showcase', 'Find glass display cases with shimmering jewelry, rings, necklaces, and watches lit from within to sparkle and shine.', 'Show jewelry, watches, rings, necklaces, or precious items displayed in a lit showcase or window with reflective display surfaces.', 'uncommon'::public.item_rarity, 'Jewelry store windows use black velvet backgrounds because the human eye perceives diamonds as brighter when surrounded by absolute darkness.', 'https://upload.wikimedia.org/wikipedia/commons/1/18/Halls_Logo.svg', 11),
    ('Restaurant window seating view', 'Look through the glass at diners seated by the window eating and enjoying meals, showing the cozy interior life.', 'Capture diners seated inside visible through the storefront window, with tables, place settings, or food service visible indoors.', 'common'::public.item_rarity, 'Busy restaurants intentionally seat customers at windows—full-window diners attract pedestrian foot traffic by appearing exclusive and sought-after.', 'https://upload.wikimedia.org/wikipedia/commons/9/91/The_oldest_operating_McDonald%27s_restaurant_was_the_third_one_built%2C_opening_in_1953._It_is_located_at_10207_Lakewood_Blvd._at_Florence_Ave._in_Downey%2C_California.png', 12),
    ('Corner store facade', 'Capture the architectural front of a small neighborhood shop positioned at a street corner with its entrance and signage visible.', 'Display a store building at a street corner with two visible storefront faces meeting at a 90-degree angle with distinct window or door frontage.', 'common'::public.item_rarity, 'Corner stores occupy the most expensive real estate partly because two street frontages create dual window displays, multiplying visibility.', 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Jenners_department_store%2C_Princes_Street%2C_Edinburgh.JPG', 13),
    ('Illuminated product display', 'Photograph merchandise lit by spotlights or backlighting that makes products stand out brightly against the darker window.', 'Show merchandise or products brightly lit by interior or decorative lighting, clearly visible and highlighted within the storefront window.', 'uncommon'::public.item_rarity, 'Warm lighting (2700K) increases purchase intent for clothing; cool lighting (5000K) increases it for electronics—different wavelengths trigger different buying impulses.', 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Seven_segment_01_Pengo.jpg', 14)
) as x(name, description, ai_validation_prompt, rarity, fun_fact, example_image_url, sort_order);
