-- Migration: achievement_reactions_given_100
-- Auto-generated by scripts/generate-achievement.ts. Review the proposal in
-- the PR description before merging — Claude can be fooled into proposing
-- duplicates the cross-check missed (e.g. semantic dup with a different code).
--
-- Rollback:
--   delete from public.achievements where code = 'reactions_given_100';

insert into public.achievements (code, title, description, icon, xp_reward, condition, sort_order)
values (
  'reactions_given_100',
  'Community Champion',
  'Give reactions to 100 of your fellow photographers'' finds.',
  '🤝',
  110,
  '{"kind":"reactions_given","gte":100}'::jsonb,
  90
)
on conflict (code) do update
  set title       = excluded.title,
      description = excluded.description,
      icon        = excluded.icon,
      xp_reward   = excluded.xp_reward,
      condition   = excluded.condition,
      sort_order  = excluded.sort_order;
