-- Migration: collection_cafe_window_displays_urban_storytelling
-- Auto-generated by scripts/generate-collection.ts (multi-agent pipeline).
-- Review the title, item names, and ai_hints before merging — Claude can be
-- fooled into proposing a near-duplicate of an existing collection that the
-- normalised name check missed.
--
-- Topic rationale: Cafes are ubiquitous in every neighborhood, making their window displays highly photographable without travel. This topic is distinct from existing architecture and street art collections — it focuses on the carefully curated, changeable displays (pastries, cake stands, vintage signs, neon menus, plants, vintage furniture) that define cafe identity and appeal to everyday urban explorers.
-- Generation: model=claude-haiku-4-5-20251001 input=8028 output=3358 cache_read=0 cache_write=0
--
-- Idempotent — relies on collections_system_title_uniq (migration 015).
-- Re-applying skips the collection insert and is a no-op (items insert is
-- gated on the new id, so it only fires when the parent insert succeeded).
--
-- Rollback:
--   delete from public.collections
--    where creator_id = '00000000-0000-0000-0000-000000000001' and title = 'Cafe Window Displays: Urban Storytelling';

with new_coll as (
  insert into public.collections (
    creator_id, title, description, category, cover_image_url, is_public, is_freeform
  )
  values (
    '00000000-0000-0000-0000-000000000001',
    'Cafe Window Displays: Urban Storytelling',
    'A photographic exploration of cafe window displays across urban landscapes. This collection captures the visual narratives, design aesthetics, and cultural moments that unfold in storefront windows of coffee shops and cafes. From vintage signage and seasonal decorations to artfully arranged pastries and product displays, these photographs reveal how urban cafes present themselves to passersby and create inviting spaces that reflect neighborhood character and contemporary trends.',
    'urban'::public.collection_category,
    'https://upload.wikimedia.org/wikipedia/commons/e/e1/StateTheaterAuburnCA.jpg',
    true,
    false
  )
  on conflict (creator_id, title) do nothing
  returning id
)
insert into public.collection_items (
  collection_id, name, description, ai_validation_prompt, rarity, fun_fact, example_image_url, sort_order
)
select new_coll.id, x.name, x.description, x.ai_validation_prompt, x.rarity, x.fun_fact, x.example_image_url, x.sort_order
from new_coll
cross join (values
    ('Vintage neon cafe sign', 'Look for glowing tubes spelling out the cafe name or ''Open,'' ideally with that classic bright pink or blue neon glow catching the evening light.', 'Identify a neon sign in the window displaying cafe branding with glowing tubes forming letters or symbols typical of retro cafe aesthetics.', 'uncommon'::public.item_rarity, 'Neon gas produces red light; other colors require different noble gases—argon for blue, helium for pink.', 'https://upload.wikimedia.org/wikipedia/commons/e/e1/StateTheaterAuburnCA.jpg', 0),
    ('Espresso machine through glass', 'Spot the shiny chrome espresso machine visible through the window with its distinctive group heads and steam wand, maybe with someone actually pulling a shot.', 'Detect an espresso machine visible through the cafe window, showing its metallic body, group heads, and steam wand components.', 'common'::public.item_rarity, 'Espresso requires water at 88-92°C forced through grounds at 9+ bars of pressure to properly extract oils.', 'https://upload.wikimedia.org/wikipedia/commons/5/59/Rocket_silver_metal_espresso_machine_on_table.jpg', 1),
    ('Pastry display case', 'Find the glass-fronted case showcasing croissants, pastries, and baked goods arranged inside, usually near the counter or visible from the street.', 'Locate a glass or transparent display case in the window containing baked goods such as croissants, cakes, or pastries arranged for sale.', 'common'::public.item_rarity, 'Laminated croissants contain natural acids that prevent staling by delaying starch crystallization.', null, 2),
    ('Chalkboard menu board', 'Look for a black chalkboard with white handwritten text listing drinks and food, typically propped in the window or near the entrance.', 'Find a chalkboard sign displaying menu items, prices, or cafe information written in chalk within the window frame.', 'common'::public.item_rarity, 'Chalk''s porous surface allows it to bond with slate microscopically, which is why it marks but erases clean.', 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Menu_of_Fatto_a_Mano_Pizzeria%2C_North_Laine_%28desserts%29.jpg', 3),
    ('Potted plants and flowers', 'Notice fresh plants or flower arrangements in pots on the windowsill or entrance, adding a touch of green to the cafe''s street-facing display.', 'Spot decorative potted plants or cut flowers placed in the window sill or beside the glass creating greenery accents.', 'common'::public.item_rarity, 'Plants in cafés absorb CO2 and release oxygen, measurably improving air quality for customers.', 'https://upload.wikimedia.org/wikipedia/commons/9/94/Container_garden_on_front_porch.jpg', 4),
    ('Window reflection of street', 'Capture the mirrored image of the street, buildings, or passing people reflected in the cafe window glass layered with the cafe''s interior behind it.', 'Capture the reflection of the street scene, buildings, or pedestrians mirrored in the cafe window glass.', 'common'::public.item_rarity, 'Glass reflects roughly 4% of light per surface; storefront reflections layer multiple reflections at angles.', 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Kafka_Betrachtung_1912.jpg', 5),
    ('Hanging pendant lights', 'Look up to see decorative hanging lights suspended from the ceiling near or visible through the window, creating warm pools of light inside.', 'Observe pendant light fixtures suspended from the ceiling or overhead inside the cafe visible through the window.', 'common'::public.item_rarity, 'Edison filament bulbs waste 90% of energy as heat; modern cafés increasingly switch to LEDs for cost.', 'https://upload.wikimedia.org/wikipedia/commons/9/91/PH-Lampan_1.jpg', 6),
    ('Artisan coffee bags', 'Spot colorful or minimalist coffee bags with roaster names and origin labels stacked or displayed on shelves visible through the window.', 'Identify packaged coffee bags or coffee bean packaging displayed in the window with visible branding and product labels.', 'uncommon'::public.item_rarity, 'Coffee begins losing flavor 30 days after roasting as CO2 degasses; bags must allow slow oxygen exchange.', 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Sacos_de_caf%C3%A9%2C_Casa_do_Bandeirante_2.JPG', 7),
    ('Café entrance door frame', 'Frame the cafe''s actual front door and entrance with its wood or metal frame, doorknob, and the transition from street to interior space.', 'Show the cafe''s entry door within the frame, displaying the doorway structure, handle, and surrounding architectural details.', 'common'::public.item_rarity, 'Door frames are angled 5mm inward at top to ensure doors close by gravity, not springs.', 'https://upload.wikimedia.org/wikipedia/commons/7/74/Rick%27s_Caf%C3%A9_in_2011.JPG', 8),
    ('Handwritten specials sign', 'Find small handwritten signs offering daily specials or limited-time items, often taped inside the window or on the door with pen or marker.', 'Capture a sign with handwritten text advertising daily specials, offers, or featured items in the cafe window.', 'common'::public.item_rarity, 'Handwritten signage increases purchase intention by activating consumers'' mirror neurons through perceived effort.', 'https://upload.wikimedia.org/wikipedia/commons/7/76/Et_sign.svg', 9),
    ('Window seat with customers', 'Photograph people sitting at a table right against the window, enjoying drinks and food while looking out at or interacting with the street.', 'Reveal seating positioned at the window with people sitting inside the cafe visible through the glass.', 'common'::public.item_rarity, 'Humans subconsciously prefer window seats for territorial visibility; café seating reflects primal positioning instinct.', 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Window_Seats_live_2012-03-15.jpg', 10),
    ('Decorative curtains or shutters', 'Look for patterned curtains, linen panels, or wooden shutters framing the cafe window, adding texture and character to the storefront.', 'Display fabric curtains, lace panels, or window shutters hung at or framing the cafe window for aesthetic decoration.', 'uncommon'::public.item_rarity, 'Heavy drapes reduce window heat loss by up to 25% while creating cafe intimacy and diffusing harsh light.', 'https://upload.wikimedia.org/wikipedia/commons/9/95/Carlyle_Hotel_Madison_76_jeh.JPG', 11),
    ('Coffee cup and saucer display', 'Spot carefully arranged stacks of ceramic cups and saucers on shelves or countertops visible through the glass, showing the cafe''s style.', 'Show decorative coffee cups and saucers arranged in the window, either stacked, hung, or displayed as merchandise.', 'uncommon'::public.item_rarity, 'Ceramic''s thermal conductivity is low; saucers insulate cups and prevent table heat damage by design.', 'https://upload.wikimedia.org/wikipedia/commons/5/59/Coffee_at_Christmas_%28Unsplash%29.jpg', 12),
    ('Retail merchandise shelf', 'Find shelves inside displaying items for sale like mugs, candles, books, or gifts, neatly arranged and visible from the sidewalk.', 'Present a shelf or shelving unit inside the cafe window displaying retail products like mugs, candles, or gift items for sale.', 'uncommon'::public.item_rarity, 'Eye-level shelving sells 30-40% more product; cafés deliberately place premium items at customer eye height.', 'https://upload.wikimedia.org/wikipedia/commons/3/31/IBM_merchandising_coffee_mug_with_company_logo.jpg', 13),
    ('Café window condensation pattern', 'Capture the foggy, misty window with water droplets and patterns formed from temperature differences, creating a dreamy frame around the interior.', 'Capture visible water droplets, fog, or condensation patterns on the window glass creating texture and atmospheric effect.', 'rare'::public.item_rarity, 'Condensation forms where temperature gradient is steepest; its patterns reveal warm air currents from inside.', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Cloud_over_A340_wing.JPG', 14)
) as x(name, description, ai_validation_prompt, rarity, fun_fact, example_image_url, sort_order);
