-- Migration: achievement_finds_100
-- Auto-generated by scripts/generate-achievement.ts. Review the proposal in
-- the PR description before merging — Claude can be fooled into proposing
-- duplicates the cross-check missed (e.g. semantic dup with a different code).
--
-- Rollback:
--   delete from public.achievements where code = 'finds_100';

insert into public.achievements (code, title, description, icon, xp_reward, condition, sort_order)
values (
  'finds_100',
  'Finds Centennial',
  'Capture 100 finds and join the ranks of dedicated photographers.',
  '💯',
  120,
  '{"kind":"finds_count","gte":100}'::jsonb,
  90
)
on conflict (code) do update
  set title       = excluded.title,
      description = excluded.description,
      icon        = excluded.icon,
      xp_reward   = excluded.xp_reward,
      condition   = excluded.condition,
      sort_order  = excluded.sort_order;
